templates/base.html

fix `Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

enable strict mode

---

charts/series.go

Add `SymbolSize` for scatter series.
Example: https://echarts.apache.org/examples/en/editor.html?c=scatter-simple
Doc: https://echarts.apache.org/en/option.html#series-scatter.symbolSize

Add SymbolSize for scatter series

---

render/engine.go
templates/base.go

Here is a short fix for js functions to work properly without annoying escapes like "/003e" for ">" etc...
It is currently untested because I use currently only the V1 version.
I hope it helps.
Sincerely Stefan

Render Javascript methods as js and not as html

---

charts/chart3d.go

There is an unnecessary property in `Chart3D` which will cover the configurations in `setBaseGlobalOptions`. and there is no way to set the `Chart3D.Grid3D`.
```go
func (c *Chart3D) SetGlobalOptions(opts ...GlobalOpts) *Chart3D {
c.BaseConfiguration.setBaseGlobalOptions(opts...)
return c
}
```
**Configuration**：
```go
charts.WithGrid3DOpts(opts.Grid3D{
BoxWidth:    160,
BoxDepth:    80,
ViewControl: opts.ViewControl{AutoRotate: true, AutoRotateSpeed: 200},
}),
```
**Before**
```go
zAxis3D: {},
grid3D: {"viewControl":{}},
series: [
```
**After**
```go
zAxis3D: {},
grid3D: {"boxWidth":160,"boxDepth":80,"viewControl":{"autoRotate":true,"autoRotateSpeed":200}},
series: [
```

Remove unused property.

---

types/charts.go

Avoid cause error `Component series.line3d not exists. Load it first.`

Fix the wrong type name of Line3D.

---

opts/global.go
opts/global_test.go

When we use generateUniqueID() to generate ChartIDs on windows usually these are not unique, since time.Now().UnixNano() returns same values every few milliseconds on windows.
test case:
```go
func TestGenerateUniqueID(t *testing.T) {
var old string
for i := 0; i < 10; i++ {
new := generateUniqueID()
assert.NotSame(t, old, new)
old = new
}
}
```

Fix generateUniqueID() returns same strings on windows

---

charts/series.go
charts/sunburst.go
opts/charts.go
opts/global.go
opts/series.go
types/charts.go

- `WithSunburstOpts `
- `NewSunburst`
```go
package main
import (
"math/rand"
"os"
)
// generate random data for bar chart
func generateBarItems() []opts.SunBurstData {
items := make([]opts.SunBurstData, 0)
for i := 0; i < 7; i++ {
items = append(items, opts.SunBurstData{
Value: rand.Float64(),
Name:  "11111",
Children: []*opts.SunBurstData{
{
Value: rand.Float64(),
Name:  "2222",
},
},
})
}
return items
}
func main() {
sunburst := charts.NewSunburst()
sunburst.SetGlobalOptions(
charts.WithTitleOpts((opts.Title{Title: "Sunburst"})),
)
sunburst.AddSeries("sunburst", generateBarItems()).SetSeriesOptions(
charts.WithLabelOpts(
opts.Label{
Show:      true,
Formatter: "12345s",
},
), …
```

Feat: basic sunburst chart

---

charts/series.go
charts/tree.go
opts/charts.go
opts/series.go
types/charts.go

**Tree**
**Example**
```go
package main
import (
"os"
"io"
"github.com/go-echarts/go-echarts/v2/components"
)
func main() {
tree := charts.NewTree()
tree.SetGlobalOptions(
charts.WithTitleOpts(opts.Title{Title: "Tree Chart"}),
charts.WithToolboxOpts(opts.Toolbox{
Show: true,
Feature: &opts.ToolBoxFeature{
SaveAsImage: &opts.ToolBoxFeatureSaveAsImage{
Show:  true,
Type:  "png",
Title: "Download as PNG",
},
},
}),
charts.WithLegendOpts(opts.Legend{Show: true}),
charts.WithTooltipOpts(opts.Tooltip{Show: true}),
)
chield1 := &opts.TreeData{
Name: "test2",
Value: 2,
}
chield2 := &opts.TreeData{
Name: "test3",
Value: 3,
}
children := make([]*opts.TreeData, 0)
children = append(children, chield1)
children = …
```

feat/tree: add tree chart type

---

charts/bar3d.go

Fixed typo that was causing Bar3D struct to render Scatter3D charts.

Bar3D struct should produce Bar3D charts

---

charts/series.go
opts/charts.go

https://echarts.apache.org/en/option.html#series-line.showSymbol
Allow configure showSymbol to hide markers in line charts.

Add ShowSymbol option for line

---

charts/bar.go
charts/base.go
charts/chart3d.go
charts/funnel.go
charts/gauge.go
charts/geo.go
charts/heatmap.go
charts/kline.go
charts/liquid.go
charts/map.go
charts/parallel.go
charts/pie.go
charts/radar.go
charts/rectangle.go
charts/sankey.go
charts/series.go
charts/themeriver.go
charts/tree.go
charts/wordcloud.go
components/page.go
opts/global.go
opts/series.go
render/engine.go

I refactored and completed some unfinished comments. I mainly followed practices mentioned in [Effective Go](https://golang.org/doc/effective_go#commentary):
> All comments should start with a whitespace.
Comments of exported functions should begin with the name being declared.
Comments should be meaningful or they should be removed.
However, please feel free to edit or make any changes you deem necessary.

Refactor incomplete comments of exported functions

---

charts/base.go
opts/series.go
templates/base.go

This change resolves the issue with the formatter.
When we use characters like "&" inside the formatters, they were automatically escaped as HTML and nothing could be done about it. As a result, a code like `if (true && true) { return 'something' }` made HTML invalid.

fix an escaping of JS code

---

opts/charts.go

There was a problem, because of the int type of Category field and annotation "omitempty". The zero index was never marshaled in the template as a category.

Fixed a non-clickable category on the graph chart

---

charts/series.go
opts/charts.go

With this change it is possible to set Step to all possible options, according to https://echarts.apache.org/en/option.html#series-line.step:
true, false, "start", "middle", "end"

Change Step from bool to interface{} to allow string options

---

opts/global.go

Add property AlignWithLabel to structs AxisTick and SplitLine.
Echarts docs has reference to AlignWithLabel for AxisTick, but no
reference for SplitLine. But in fact SplitLine also support this
feature.

Add property AlignWithLabel to structs AxisTick and SplitLine

---

charts/bar.go
charts/base.go
charts/boxplot.go
charts/chart3d.go
charts/effectscatter.go
charts/funnel.go
charts/gauge.go
charts/geo.go
charts/graph.go
charts/heatmap.go
charts/kline.go
charts/line.go
charts/liquid.go
charts/map.go
charts/parallel.go
charts/pie.go
charts/radar.go
charts/sankey.go
charts/scatter.go
charts/series.go
charts/sunburst.go
charts/themeriver.go
charts/tree.go
charts/treemap.go
charts/wordcloud.go
opts/global.go

axisPointers can be linked to each other. The term "link" represents that axes are synchronized and move together. Axes are linked according to the value of axisPointer.
the `series.configureSeriesOpts` method should pub for easy configuration of series individually.
like 
``` go
func AddMarkPoint(kline *charts.Kline, seriesIndex int, text string, Color string, x interface{}, y interface{}) {
if len(kline.MultiSeries) > seriesIndex {
kline.MultiSeries[seriesIndex].ConfigureSeriesOpts(
charts.WithMarkPointNameCoordItemOpts(opts.MarkPointNameCoordItem{
Name:       text,
Coordinate: []interface{}{x, y},
Label: &opts.Label{
Show:      true,
Formatter: text,
},
ItemStyle: &opts.ItemStyle{
Color: Color,
Opacity: 0.8,
},
}),
)
}
}
```
refer: …

add axisPointers.Link opt

---

charts/series.go
opts/series.go

impl missing mark areas
```go
charts.WithMarkAreaNameCoordItemOpts(opts.MarkAreaNameCoordItem{
Name:        "TEST",
Coordinate0: []interface{}{"25.02.22 02:30", 1.120},
Coordinate1: []interface{}{"25.02.22 10:30", 1.125},
ItemStyle: &opts.ItemStyle{
Color: "rgba(55, 173, 177, 0.4)",
},
}),
```

added mark area to charts series and opts series

---

charts/series.go

This PR fixes issues with the `Smooth` and `ConnectNulls` flag. They had `omitempty` which omitted them when they were `false` and therefore were ignored when set to `false`.
Also the `ShowSymbol` was not assigned and therefore ignored.

Do not omit empty flags (false gets omitted), correctly assign ShowSymbol

---

charts/base.go
components/page.go
opts/global.go

// TODO
For now it gonna set the init default options, but can be replaces by custom options.
Maybe we should do the `merge` opt instead of `replace` or find a way to set default val before render .
close #271

fix: default val override.

---

opts/global.go

This is another attribute I require to reproduce the colored graph shown in this example: https://echarts.apache.org/examples/en/editor.html?c=line-sections
I wanted to document `Min`, `Max`, `Lt`, `Lte`, `Gt` and `Gte` but I can't find documentation from echart where those attributes are properly described. Those values are just used in some of their examples.

Add pieces to opt.VisualMap

---

opts/global.go

I need to apply a visual map along the x axis and as far as I understand, the dimension attribute can be used to specify that which was missing from the structure.

Add dimension to opt.VisualMap

---

charts/base.go
charts/rectangle.go
charts/series.go
opts/global.go

I've been loving this library -- such a great integration of Golang <> JSON <> eCharts.    It took me a while to isolate my changes, but I finally rebased them for a PR.   Since one has a breaking change, maybe you want to separate it and I will if you ask me to.
Three changes, one adds some missing fields:
* Tooltip.ValueFormatter
* AxisPointer.Show
* AxisPointer.Label
* AxisLabel.BackgroundColor
* XAxis.AxisPointer
* YAxis.AxisPointer
* DataZoom.LabelFormatter
Another strips `//` comments from JavaScript code, while still having `FuncNoStripOpts` if somehow that's not wanted.  But most JavaScript code will.   This makes using `go:embed` much easier (which I'll add a PR to `examples` about).
The last adds support for multiple datasets. …

NM Various Enhancements

---

render/engine.go

Calls `.Funcs` before `.Parse` as is mentioned here: https://pkg.go.dev/text/template#Template.Funcs
Fixes #292 
---

fix(render):musttemplate adds funcs to template before parsing

---

opts/global.go

Add nameLocation config.
Close #290 
---
---

update: add nameLocation config.

---

opts/charts.go

Adds `Tooltip` field to `GraphNode` to allow configuration of tooltip on a per-node basis.
Fixes #304
---

feat: added tooltip property to graph node

---

opts/series.go

Some of the dataset encoding parameters for series are not included in the `opts/series` encoding options. This MR adds the missing options.
The echarts documentation that is already linked in the code here shows these options.
Fixes #302 
---

feat: encode properties for any series dataset added

---

charts/radar.go
charts/series.go
opts/charts.go

Supports `symbolkeepAspect` option for graph series.
Fixes #306
---
---

feat: added symbolKeepAspect option to graph series

---

opts/global.go

Adds `nameGap` to x and y axis options.
Fixes #323.

Add nameGap to x and y axis options

---

charts/base.go
charts/heatmap.go
charts/series.go
opts/global.go
types/orderedset_test.go

The library only supports the traditional heatmap. echarts supports also the [calendar variation](https://echarts.apache.org/examples/en/editor.html?c=calendar-heatmap).
I added the support for the calendar. It's now possible to add multiple series and multiple calendars
---
---
This is how I use it go potentially generate a set of multiple calendars per year. After the code you can find the generated calendar (only for 1 year).
```go
var dailyStepsPerYear map[int][]opts.HeatMapData = make(map[int][]opts.HeatMapData)
var maxSteps int = 0
for _, dayData := range all {
if dayData == nil || dayData.Steps == nil {
continue
}
step := int(dayData.Steps.Value)
if step > maxSteps {
maxSteps = step
}
// format date to YYYY-MM-DD
value := [2]interface{}{dayData.Date.Format(time.DateOnly), step} …
```

Added calendar support

---

opts/js.go
render/engine.go
templates/base.tpl

Expose echarts instance as `%MY_ECHARTS%` to allow user to access it in JS funcs.
> Please share your ideas and awesome changes.
---
---
If there contains a branch new features of chart, are you willing to submit a PR
> charts examples to more users.

feat: expose echarts instance

---

components/page.go
opts/global.go

Since the `page` and `chart` have the same `opts.Initialization`, it get misunderstanding easily.
Changes:
- Move the Page's config as `PageConfiguration`. Charts' options is invisible for page.
- Keep it duplicated page config in `opts.Initialization` instead nest `PageConfiguration` for compatibility.
close #355 
---

fix: page config mess up with chart

---

charts/series.go

The RoseType has bool and string types (same effects), fix it as string only.
---
---

fix: RoseType type inconsistent

---

charts/series.go
opts/charts.go
opts/title.go

Add options to create a gauge chart like this:
It is inspired by this: https://echarts.apache.org/examples/en/editor.html?c=gauge-speed
---
The following options are now available for a gauge chart:
- Progress
- AxisTick (settings this on XAsis does not work)
- Detail
---
Once this PR is merged, I will create a PR for the examples repo.

feat(gauge): add options 'progress', 'axistick' and 'detail'

---

opts/y_axis.go

update(opt): add min/maxInterval opt

---

charts/base.go
opts/charts.go
opts/polar.go

Fix the `Polar` config which maintain with `hasPolar`, close #414 .
> Fixed output
```go
const numPoints = 100
data := make([]opts.LineData, numPoints)
for ii := range 100 {
theta := (float64(ii) / numPoints) * 360.0
r := 5 * (1.0 + math.Sin((theta/180)*math.Pi))
data[ii] = opts.LineData{Value: []float64{r, theta}}
}
polar := charts.NewLine()
polar.SetGlobalOptions(
charts.WithPolarOps(opts.Polar{}),
charts.WithTitleOpts(opts.Title{Title: "Two Value-Axes in Polar"}),
charts.WithTooltipOpts(
opts.Tooltip{
Show:        opts.Bool(true),
Trigger:     "axis",
AxisPointer: &opts.AxisPointer{Type: "cross"},
}),
charts.WithAngleAxisOps(opts.AngleAxis{
PolarAxisBase: opts.PolarAxisBase{
Type:       "value",
StartAngle: 0.0,
},
}),
charts.WithRadiusAxisOps(opts.RadiusAxis{}),
)
polar.AddSeries( …
```

fix: fix polar config setup

---

charts/series.go
opts/gauge.go

Add the `Min`/`Max` config in series, specially for Gauge now. see #419 
With the `WithSeriesOpts` helper to achieve it for now. need restructure the series of Gauge later.
---
---

update: add series options Min Max.

---

opts/series.go

As discussed in #456 .
It is missing config the mark line style per data:
```js
option = {
tooltip: {},
legend: {},
xAxis: {
data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
},
yAxis: {},
series: [{
name: "Sale",
type: "bar",
data: [5, 20, 36, 10, 10, 20, 4],
markLine: {
data: [{
type: "average",
// here
lineStyle: {
color: "rgba(105, 36, 36, 1)"
}
},{
type: "max"
}],
}
}]
}
```
---
---

fix(options): allow set markline style per data

---

opts/charts.go

echarts.apache.org support customization of styles for Graph edges, Graph Category nodes, etc.
- https://echarts.apache.org/en/option.html#series-graph.links
- https://echarts.apache.org/en/option.html#series-graph.categories
The change allows advance visualisation of graphs:
---
---

Style config for Graph elements

---

opts/series.go

// Origin position of area.
// By default, the area between axis line and data will be filled.
// This config enables you to fill the area from data to the max or min of the axis data or a specified value.
// Valid values:
// 'auto' to fill between axis line and data (Default)
// 'start' to fill between min axis value (when not inverse) and data
// 'end' to fill between max axis value (when not inverse) and data
//  number to fill between specified value and data
---
---

update(opt): add position of area config

---

opts/radar.go

add startAngle option.
```go
package main
import (
"os"
)
var indicators = []*opts.Indicator{
{Name: "AQI", Max: 300},
{Name: "PM2.5", Max: 250},
{Name: "PM10", Max: 300},
{Name: "CO", Max: 5},
{Name: "NO2", Max: 200},
{Name: "SO2", Max: 100},
}
func main() {
radar := charts.NewRadar()
radar.SetGlobalOptions(
charts.WithTitleOpts(opts.Title{
Title: "basic radar example",
}),
charts.WithRadarComponentOpts(opts.RadarComponent{
Indicator:  indicators,
SplitArea:  &opts.SplitArea{Show: opts.Bool(true)},
SplitLine:  &opts.SplitLine{Show: opts.Bool(true)},
AxisLine:   &opts.AxisLine{Show: opts.Bool(false)},
StartAngle: 45,
}),
)
radar.AddSeries("Data", []opts.RadarData{{Value: []int{57, 31, 54, 1, 32, 14, …
```

radar start angle option

---

opts/series.go

This PR adds the [areaColor](https://echarts.apache.org/en/option.html#geo.itemStyle.areaColor) to the `ItemStyle` options.
It can be used to set the fill color of map tiles.
---

Add AreaColor to ItemStyle

---

opts/radar.go

Allows customisation of radar indicators.
[echarts docs - radar.axisName](https://echarts.apache.org/en/option.html#radar.axisName)
```go
package main
import (
"os"
)
var indicators = []*opts.Indicator{
{Name: "AQI", Max: 300},
{Name: "PM2.5", Max: 250},
{Name: "PM10", Max: 300},
{Name: "CO", Max: 5},
{Name: "NO2", Max: 200},
{Name: "SO2", Max: 100},
}
func main() {
radar := charts.NewRadar()
radar.SetGlobalOptions(
charts.WithTitleOpts(opts.Title{
Title: "basic radar example",
}),
charts.WithRadarComponentOpts(opts.RadarComponent{
Indicator: indicators,
SplitArea: &opts.SplitArea{Show: opts.Bool(true)},
SplitLine: &opts.SplitLine{Show: opts.Bool(true)},
AxisLine:  &opts.AxisLine{Show: …
```

radar axisName option

---

opts/x_axis.go

Currently there is no way to style the `XAxis` in the contrast to `YAxis`
As stated in the Apache Echarts official documentation ([here](https://echarts.apache.org/en/option.html#xAxis.axisLine)), there is an `axisLine` property for both `xAxis` and `yAxis`, however currently only `yAxis` has that property exclusively. By adding it also to `XAxis` the styling, (not)-showing the axis can be configured, as is depicted on the following screenshots:

update(opt): add AxisLine to XAxis

---

charts/base.go
charts/map.go
datasets/mapfiles.go

Appending the preset geo file when its map type is matched.
---
---

update(map): refine register map type

---

opts/tooltip.go

https://echarts.apache.org/en/option.html#grid.tooltip.position
I was seeking to do tooltip positioning like [this ECharts candlestick example](https://echarts.apache.org/examples/en/editor.html?c=candlestick-brush), but discovered that it wasn't exposed by `go-echarts`.
I added the binding to it.   I tested it with positioning code there :
```javascript
// tooltipPositioner.js
function (pos, params, el, elRect, size) {
const obj = {
top: 10
};
obj[['left', 'right'][+(pos[0] < size.viewSize[0] / 2)]] = 30;
return obj;
}
```
```golang
//go:embed js/tooltipPositioner.js
var tooltipPositioner string
func makeCharts() {
......
charts.WithTooltipOpts(opts.Tooltip{
Show:        opts.Bool(true),
Trigger:     "axis",
AxisPointer: &opts.AxisPointer{Type: "line"},
Position: …
```

Add tooltip.Position function

---

charts/series.go
opts/series_bar.go

Added the missing BarWidth option to the BarChart type. 
---
---

added BarWidth property to opts.BarCharts

---

charts/series.go
docs/en-us/options/series.md

Allows setting the series id using `charts.WithId`:
```go
line.AddSeries("series-name", data, charts.WithSeriesId("a"))
```
Fixes #453
---
---

Add series id

---

opts/series.go

This fixes a problem where you could not remove an area fill from an existing chart that was updated with replaceMerge, because the opacity was not serialized when set to 0.
---
---

Support setting area opacity to 0

---

opts/calendar.go

Add a missing firstDay option for calendar
https://echarts.apache.org/en/option.html#calendar.dayLabel.firstDay
* Add field FirstDay in strut CalendarLabel
---
---

update(opt): add calendar.dayLabel. firstDay
