- README.md
Hi! I've just added link to godoc to README
> Add link to godoc

- README-en.md
Translate README.md to English.
> translate readme to english

- charts/bar.go
- charts/bar3D.go
- charts/base.go
- charts/boxplot.go
- charts/chart3d.go
- charts/chartRect.go
- charts/components.go
- charts/effectscatter.go
- charts/funnel.go
- charts/gauge.go
- charts/geo.go
- charts/graph.go
- charts/heatmap.go
- charts/kline.go
- charts/line.go
- charts/line3D.go
- charts/liquid.go
- charts/map.go
- charts/page.go
- charts/parallel.go
- charts/pie.go
- charts/radar.go
- charts/sankey.go
- charts/scatter.go
- charts/scatter3D.go
- charts/series.go
- charts/surface3D.go
- charts/themeRiver.go
- charts/wordcloud.go
Add comments on exported types and methods, to make golint happy.
> add comments on exported types and methods

- charts/wordcloud.go
- templates/routers.html
fix the chart selector on the top right of page even if the scroll bar slides down
> update routers.html css style

- charts/series.go
Add WithAreaStyleOpts.
```go
charts.WithAreaStyleOpts(
opts.AreaStyle{
Opacity: 0.2,
}),
```
> [refactor] Add WithAreaStyleOpts.

- charts/scatter.go
- charts/series.go
- opts/charts.go
> [refactor] ScatterData.

- charts/boxplot.go
add self validate for boxplot.
> [update] add self validate for boxplot.

- opts/charts.go
> [refactor] LiquidData.

- charts/effectscatter.go
- opts/charts.go
[refactor] add EffectScatterData & Validate.
> [refactor] add EffectScatterData & Validate.

- charts/heatmap.go
- opts/charts.go
> [refactor] heatmap.

- _examples/main.go
Ideally this is non-controversial :)
> Issue: #96 should be closed when this commits.

- charts/geo.go
- opts/charts.go
// TODO: refactor `GeoComponentOpts` to `GeoComponent`.
> [refactor] fix geo congratulations.

- charts/base.go
- charts/geo.go
- opts/global.go
1. Move the `GeoComponent` config from `Geo` to `Global` as `Radar`.
2. Add `WithGeoComponentOpts`  options.
3. Add extra configurations in `GeoComponent`.
> [refactor] Geo.

- opts/global.go
Add more options of Legend to make it flexible.
> [feat] add more options of Legend.

- opts/global.go
> [refine] replace `charts.LegendOpts{Data: []string{}},` to `Show` in Legend.

- charts/graph.go
- charts/series.go
- opts/charts.go
- opts/series.go
> [refactor] graph.go

- opts/global.go
> [update code annotation] global.go.

- opts/charts.go
Added some additional options for Sankey Chart nodes based on options at https://echarts.apache.org/en/option.html#series-sankey.nodes
> Added depth and styling options for sankey nodes

- charts/series.go
- opts/series.go
1.增加markline的坐标方法和style方法
2.增加markpoint的value, 可以在point上显示值
> add mark point value & mark line coords

- charts/graph.go
- charts/series.go
- opts/charts.go
Implemented property draggable of the original series-graph class
By https://echarts.apache.org/en/option.html#series-graph.draggable
> Added graph property draggable 

- charts/graph.go
- charts/series.go
- opts/charts.go
Implemented properties edgeSymbol and edgeSymbolSize of the original series-graph class.
By https://echarts.apache.org/en/option.html#series-graph.edgeSymbol
> Added graph edge settings

- charts/series.go
- opts/charts.go
- opts/series.go
Useful property for pretty graph 🙂
> Added edge label for graph

- opts/charts.go
- opts/global.go
- opts/series.go
> Fix minor typos in comments

- charts/series.go
- opts/series.go
https://echarts.apache.org/en/option.html#series-graph.circular.rotateLabel
> Add circular rotateLabel option in series

- charts/base.go
- opts/global.go
https://echarts.apache.org/zh/option.html#visualMap-piecewise.left
> add left,right,top and bottom to opts.VisualMap

- opts/global.go
[add show to opts.VisualMap](https://echarts.apache.org/zh/option.html#visualMap-continuous.show)
> add show to opts.VisualMap

- opts/series.go
add more options for MarkPoint and Label
> more options

- opts/global.go
> update: expose enterable.

- .github/workflows/ci.yml
Add ci build github action in github side to build project as well.
> ci: add test action.

- render/engine.go
- templates/base.go
> fix: fix base actions issue.

- README.md
- README_CN.md
> update: readme ci status.

- charts/series.go
- opts/charts.go
- opts/global.go
Add additional Line series options:
https://echarts.apache.org/en/option.html#series-lines.symbol
https://echarts.apache.org/en/option.html#series-lines.symbolSize
Add additional CandleStick series options:
https://echarts.apache.org/en/option.html#series-candlestick.barWidth
> More customizations for Line chart and Candlestick chart

- charts/chart3d.go
- components/page.go
- opts/global.go
- types/orderedset.go
> fix: echarts upgrade breaking 3d charts.

- opts/global.go
> fix: ToolBoxFeatureSaveAsImage.

- opts/global.go
Fixes #326.
- [*] New feature (Non-breaking change which adds functionality)
```go
charts.WithToolboxOpts(opts.Toolbox{
Show: true,
Feature: &opts.ToolBoxFeature{
Restore: &opts.ToolBoxFeatureRestore{
Show: true,
},
UserDefined: map[string]opts.ToolBoxFeatureUserDefined{
"myTool": {
Show:  true,
Title: "Tool example",
Icon:  "path://M432.45,595.444c0,2.177-4.661,6.82-11.305,6.82c-6.475,0-11.306-4.567-11.306-6.82s4.852-6.812,11.306-6.812C427.841,588.632,432.452,593.191,432.45,595.444L432.45,595.444z M421.155,589.876c-3.009,0-5.448,2.495-5.448,5.572s2.439,5.572,5.448,5.572c3.01,0,5.449-2.495,5.449-5.572C426.604,592.371,424.165,589.876,421.155,589.876L421.155,589.876z M421.146,591.891c-1.916,0-3.47,1.589-3.47,3.549c0,1.959,1.554,3.548,3.47,3.548s3.469-1.589,3.469-3.548C424.614,593.479,423.062 …
```
> Add support for user-defined tools

- .github/workflows/ci.yml
- charts/base.go
- charts/series.go
- components/page.go
- opts/global.go
- opts/global_test.go
- opts/js.go
- opts/radar.go
- opts/visual_map.go
- types/primitivie.go
- util/default_val_setter.go
- util/id_gennerator.go
Polish util and comments.
---
---
> chore: polish

- charts/base.go
- event/event.go
- templates/base.tpl
see #337 
> Please share your ideas and awesome changes.
---
---
If there contains a branch new features of chart, are you willing to submit a PR
> charts examples to more users.
> feat: event support

- opts/global.go
- templates/base.tpl
Adds support for SVG renderer.
Fixes #165.
> Support svg renderer

- charts/base.go
- event/event.go
- templates/base.tpl
Fix the #334  render issue and polish the EventListener.
> Please share your ideas and awesome changes.
---
---
If there contains a branch new features of chart, are you willing to submit a PR
> charts examples to more users.
> fix: fix render and polish

- README.md
Thx for those contributors who integrate with gp-echarts in awesome.
close #335 
<!-- Please include a summary of the change or which issue is fixed. Please also include relevant motivation and context.
List any dependencies/documents that are required for this change is a plus.
> update: new Ecosystem topic on templ support

- render/engine.go
- templates/base.tpl
> Please share your ideas and awesome changes.
Filter not config action to make render clean.
---
---
If there contains a branch new features of chart, are you willing to submit a PR
> charts examples to more users.
> update: action filter tpl function

- opts/title.go
Add border opts.
TODO: with opts functions after options stuff done.
---
---
> update: title border opts

- opts/text_style.go
Add font opts, and it seems nest font struct is possible.
---
---
> update: text_style font opt

- opts/global.go
- types/orderedset.go
Allow to clear all the preset assets instead of only host customized.
---
---
> update: allow clean assets

- opts/grid.go
> update: opts for grid sync

- charts/series.go
- opts/grid.go
> fix: expose SymbolKeepAspect from series

- opts/x_axis.go
> update: x_axis opt

- charts/series.go
Because currently those `WithXXX` function if not fully contains all opts for each charts on series level.
Expose a way to fully configurable.
---
---
> update: expose series

- render/chart.go
- render/engine.go
- render/page.go
Expose the rendered bytes content .
---
---
> update: expose content

- opts/polar.go
- opts/radius_axis.go
> update: opts polar radius_axis

- charts/series.go
> add: series opt large

- charts/series.go
Try to find a way to better manage series vary from charts.
---
---
> update: series opts rich

- .gitignore
- docs/_sidebar.md
- docs/en-us/charts/kline.md
- docs/en-us/charts/map.md
- docs/en-us/charts/pie.md
- docs/en-us/charts/scatter.md
> docs: map pie kline scatter examples

- docs/_sidebar.md
- docs/en-us/charts/boxplot.md
- docs/en-us/charts/graph.md
- docs/en-us/charts/heatmap.md
- docs/en-us/charts/radar.md
> docs: radar boxplot heatmap graph examples

- docs/_sidebar.md
- docs/en-us/charts/parallel.md
- docs/en-us/charts/sankey.md
- docs/en-us/charts/sunburst.md
- docs/en-us/charts/tree.md
- docs/en-us/charts/treemap.md
> docs: tree treemap parallel sankey sunburst examples

- docs/_sidebar.md
- docs/en-us/charts/bar3d.md
- docs/en-us/charts/line3d.md
- docs/en-us/charts/scatter3d.md
- docs/en-us/charts/surface3d.md
> docs: bar3d scatter3d surface3d line3d examples

- docs/_sidebar.md
- docs/en-us/charts/liquid.md
- docs/en-us/charts/wordcloud.md
> docs: 3rd charts liquid wordcloud examples

- charts/series.go
Move the `Animation` configs to custom part. and try to manage all options in `series` as well.
---
---
> chore: restruct animation opts

- charts/series.go
> update: barWidth series

- charts/series.go
- opts/charts.go
- opts/series_bar.go
> update: series bar refactor

- charts/series.go
- opts/charts.go
- opts/series_pie.go
> update: series pie refactor

- docs/_sidebar.md
- docs/en-us/options/global.md
> docs: global options

- charts/series.go
- opts/charts.go
- opts/series_scatter.go
> update: series scatter refactor

- opts/series.go
> update: label opt detail

- README.md
- README_CN.md
> chore: sync CN EN readme

- docs/en-us/options/global.md
> docs: how to define chart in go-echarts

- docs/en-us/options/global.md
> docs: overlap details

- opts/x_axis.go
> fix: wrong type in FontSize

- opts/charts.go
> fix: treemap align to other data types

- charts/series.go
- opts/series_effect_scatter.go
> add: effect scatter series

- charts/series.go
- opts/series_radar.go
> add: radar series

- .github/pull_request_template.md
> chore(tpl): add docs in type of change

- README.md
- docs/README.md
- docs/en-us/README.md
Set text-decoration to none to disable ugly underline.
---
---
> chore: set text-decoration none

- README.md
- charts/series.go
- opts/legend.go
> update: remove unused bool default val

- charts/series.go
- opts/charts.go
- opts/series.go
- opts/title.go
> chore: format comments

- docs/_sidebar.md
- docs/en-us/event-and-action.md
- docs/en-us/options/global.md
Update the option details and polish.
---
---
> docs: update options detail

- docs/index.html
update docs header meta in HTML for SEO.
---
---
> docs: head meta

- README.md
As the mentioned in #410 , GoBN has a nice support of go-echarts for NB.
---
---
> update(readme): gonb integration

- docs/en-us/event-and-action.md
Hello! The go sample code on the 'Event And Action' page of the document was incorrect, so I fixed it.
https://go-echarts.github.io/go-echarts/#/en-us/event-and-action?id=action
---
---
> docs: fix event-and-action

- README.md
- docs/_sidebar.md
- docs/en-us/ecosystem.md
Refine the `ecosystem` section in docs.
---
---
> update(docs): ecosystem contributions refinement

- docs/_sidebar.md
- docs/en-us/options/series.md
> docs: series options details and usage

- docs/_sidebar.md
- docs/en-us/render.md
- docs/index.html
Add details about renders, especially render snippets.
---
---
> docs: add render interface details

- docs/_coverpage.md
- docs/en-us/render.md
- Add example in coverage.
- Refine the renderer part
---
---
> docs: add example in coverpage

- charts/series.go
> chore: note the SetSeriesOptions usage

- opts/legend.go
> update(legend): itemStyle for legend

- charts/series.go
- opts/series.go
> update(markArea): add new MarkAreaData to suit data struct

- docs/_sidebar.md
- docs/en-us/options/xAxis.md
- docs/en-us/options/yAxis.md
> docs(option): add x y axis  option config

- opts/series.go
> update(markline): add new options for mark line

- charts/series.go
- opts/series.go
> update: add animation opt helper for series

- components/page.go
- templates/page.tpl
The version v2.4.0 has broken the compatibility with v2.3.x where application had ability to define Width and Height for the page. Making it possible to stretch graph for entire browser window. This change introduces new layout to fix the issue.
---
> feat(tpl): add new page full screen layout

- opts/data_zoom.go
- opts/x_axis.go
- opts/y_axis.go
Some additions that where usefull in my context
- dataZoom.orient
- axisLabel.AlignMinLabel, .AlignMaxLabel, .HideOverlap, .Width, .Height, .Overflow, .Ellipss
- yaxis.inverse
---
- [X ] New feature (Non-breaking change which adds functionality)
---
> Some Opts additions

- build.sh
- charts/base.go
- opts/axis_pointer.go
- opts/brush.go
- opts/dataset.go
- opts/global.go
- opts/js.go
- opts/polar.go
- opts/series.go
- opts/toolbox.go
- opts/x_axis.go
- render/render.go
- types/primitivie.go
> chore: add gofumpt linter

- charts/base.go
simply add base config without a helper method (TBD).
---
New feature
---
> update(opt): add anime opts for base config

- .github/workflows/ci.yml
- opts/y_axis.go
> update(opt): add position for y axis

- opts/data_zoom.go
> update(opt): add FilterMode for data zoom 

- opts/x_axis.go
> fix(opt): refine axislabel formmatter to func str

- docs/en-us/ecosystem.md
Add insyra into ecosystem section.
close #486 
---
---
> docs(eco): add insyra as the ecosystem part

- opts/charts.go
- opts/series_bar.go
- opts/series_effect_scatter.go
- opts/series_line.go
- opts/series_pie.go
- opts/series_radar.go
> update(opt): refine series per chart

- opts/radar.go
Ability to configure axis line in radar component.
```go
package main
import (
"os"
)
var indicators = []*opts.Indicator{
{Name: "AQI", Max: 300},
{Name: "PM2.5", Max: 250},
{Name: "PM10", Max: 300},
{Name: "CO", Max: 5},
{Name: "NO2", Max: 200},
{Name: "SO2", Max: 100},
}
func main() {
radar := charts.NewRadar()
radar.SetGlobalOptions(
charts.WithTitleOpts(opts.Title{
Title: "basic radar example",
}),
charts.WithRadarComponentOpts(opts.RadarComponent{
Indicator: indicators,
SplitArea: &opts.SplitArea{Show: opts.Bool(true)},
SplitLine: &opts.SplitLine{Show: opts.Bool(true)},
AxisLine:  &opts.AxisLine{LineStyle: &opts.LineStyle{Color: "red"}},
}),
)
radar.AddSeries("Data", []opts.RadarData{{Value: …
```
> radar: axis line option

- charts/series.go
- opts/charts.go
> ## 实现360度进度仪表盘展示
- 新增功能：设置轴线样式和可选隐藏刻度线 、刻度标签、指针等。
- 实现效果：[360度进度仪表盘](https://echarts.apache.org/examples/zh/editor.html?c=gauge-progress&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWxgCeIWxA5AOYCGAri1kwDRUUMYNjjABBaCwA2jWAE4ADP2ros0ACYTpsgLQAmAOxKB6ALYRoxYytim2AD2IBmBdZUQwWUwGU6M4qg26ADGwFLAOMwAxACsABwAInIAYnJ8JoIAFmzqwADuAMJhEcw4LABGbAAUSgCMTnG8ejExvAoAdAAsMQCU6UGY2bl5AEJSHJGwtW42GEP5APIAZkvYYAAaxHrKQXM5iytrAJpbGQC-O9QOEBgAMhaMgUFSD760_k9BeRDqYJmEMRmKgu50uFBAOGALBwBCIlAGc3yxDAOA4WDB1EhHA0BTYIGRqPRGXQ31-_1ggNBJmuGAAKhBggBrALExF5YhLNhSbBU2YgF5ge7QR7EwZI2Cc7lEmwgmw025scpYKSET4qNkcrnYDGwWUqEDACyeSJq6gaiVa6XAnWQMD-eG7TLiyU8mU69RYYQQFUO2ZO9k0Qk69AgHLqCwsYgkeq8KZOWMxuMAXWDsGAh09BTUxqjACIFLnYwok7yVOo2MIo6LTQMaB57TX0OaUWjU-nVpns7go0pYMXSwMAG5ctHEWqUgZnDIl6hT9Als4AbiAA)
---
---
> update(gauge): add options 'axisLabel', 'axisLine', 'splitLine' and 'pointer'

- opts/radar.go
sync the config same to #495 
---
---
> update(opt): refine the start angle consistent as float

- opts/toolbox.go
Add icon option for default toolbox feature.
---
---
> update(opt): add icon option for toolbox

- opts/title.go
> update(opt): add text align opts for title

- charts/base.go
- opts/tooltip.go
> update(opt): tooltip color opts

- charts/rectangle.go
According to the proposal in #510 to enhance the overlap.
Provide a generic `aggregate` function to allow the `merge` in a programmatic manner.
Refactor the `overlap` to `aggregation` either.
---
---
> feat(agg): support overlap with options

- render/engine.go
Remove the `isSet` function in renderer which is unused now.
---
---
> chore: remove unused isset in render

- .gitignore
- charts/base.go
- charts/visitor.go
A new visitor for customizing options more flexible!
And declare the `Visit` without pointer to avoid fully replacement issues.
```go
Visit(chart map[string]interface{})
```
---
---
> feat(opts): support visit and transformer on options

- charts/base.go
- docs/_sidebar.md
- docs/en-us/visitor.md
> docs(visitor): usage for configuration visitor

- components/page.go
- opts/global.go
- opts/global_test.go
- render/engine.go
- templates/header.tpl
Allow to add pure HTML custom headers.
---
---
> feat(headers): allow to add custom headers

- charts/base.go
> chore: fix ProgressiveThreshold  option typos

- build.sh
- charts/base.go
- types/primitivie.go
> chore: comments polish

- charts/series.go
> update(opt): add sankey node opts

- charts/base.go
- charts/visitor.go
- opts/aria.go
Add the `Enable` flag to `aria`, need verify options in furture.
close #530 
---
---
> update(opt): option aria enable

- opts/title.go
Before removing the extra space:
After removing the extra space:
---
> update(opt): remove extra space

- docs/en-us/chart-container.md
- docs/en-us/dive-into.md
simple polish doc format and content.
---
---
> docs: simple polish 

- .github/workflows/ci-push.yml
> ci: it run in pr only

- opts/series_line.go
https://github.com/go-echarts/go-echarts/issues/551
---
---
> Remove deprecated comment on `LineChart.Smooth`

- .github/workflows/ci-push.yml
- .gitignore
- opts/tooltip.go
> chore: value formatter doc

- charts/series.go
- opts/series.go
> update(opt): add label layout
